---

- name: create user group
  group:
    name: "{{ brook_group }}"
    state: present
- name: create user
  user:
    name: "{{ brook_user }}"
    group: "{{ brook_group }}"
    home: "{{ brook_working_dir }}"
- name: create brook bin dir path
  file:
    path: "{{ brook_bin | dirname }}"
    state: directory
    owner: "{{ brook_user }}"
    group: "{{ brook_group }}"
    mode: 0755
    recurse: yes
- name: download brook binary
  get_url:
    url: "{{ brook_url }}"
    dest: "{{ brook_bin }}"
    owner: "{{ brook_user }}"
    group: "{{ brook_group }}"
    mode: 0755
- name: create exec shell file
  template:
    src: brook.shell.j2
    dest: "{{ brook_exec_shell }}"
    owner: "{{ brook_user }}"
    group: "{{ brook_group }}"
    mode: 0755
- name: create the brook systemd unit file
  template:
    src: brook.unit.j2
    dest: /etc/systemd/system/{{ service_name }}.service
  when: ansible_service_mgr == "systemd"
  notify: restart {{ service_name }}
- name: enable and start the brook service
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
